apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascotas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mascotas
  template:
    metadata:
      labels:
        app: mascotas
    spec:
      containers:
        - name: app
          image: jilopezv/mascotas:1.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: mascotas
spec:
  selector:
    app: mascotas
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer